### ISSUE TITLE
Dark theme compatibility

### ISSUE THREAD

**Issue by M-Rick** [rizmut/libreoffice-style-sukapura#31]
The theme is not really usable in dark theme mode because icons are missing of contrast with the background.

**Comment by rizmut** [comment]
Sukapura is meant to be used for macOS platform, while currently LibreOffice support for dark mode in macOS is on a sad state See [tdf#118017](https://bugs.documentfoundation.org/show_bug.cgi?id=118017). You can try Colibre dark where Colibre is the foundation for Sukapura

**Comment by sierkb** [comment]
> Sukapura is meant to be used for macOS platform, while currently LibreOffice support for dark mode in macOS is on a sad state See [tdf#118017](https://bugs.documentfoundation.org/show_bug.cgi?id=118017). You can try Colibre dark where Colibre is the foundation for Sukapura

The formerly sad state of LO dark mode in macOS has evolved and improved significantly in the last several days and can be tested in recent daily dev builds. Please provide Sukapura Dark theme icons, so that the Sukapura theme can be used also in dark mode – LO uses the Breeze dark theme instead meanwhile because of lacking Sukapura dark theme icons, when automatically detecting dark mode from system settings.

See the improvements/patches on
[tdf#152183](https://bugs.documentfoundation.org/show_bug.cgi?id=152183)
[tdf#152184](https://bugs.documentfoundation.org/show_bug.cgi?id=152184)

**Comment by rizmut** [comment]
> The formerly sad state of LO dark mode in macOS has evolved and improved significantly in the last several days and can be tested in recent daily dev builds. Please provide Sukapura Dark theme icons, so that the Sukapura theme can be used also in dark mode – LO uses the Breeze dark theme instead meanwhile because of lacking Sukapura dark theme icons, when automatically detecting dark mode from system settings.
> 
Yes I have already now this improvement, so that's why I ask TDF staff to fire up a vote to choose exusting dark icon theme in macOS dark UI. Visit [the poll.](https://fosstodon.org/@libodesign/109414678200831831) But meantime, there's discussion in Telegram group wether macOS should stick to Sukapura or use Colibre also just like Windows counterpart. I have no strong preference here but the availability of Sukapura Dark version will not occur in a short time.

**Comment by sierkb** [comment]
> > The formerly sad state of LO dark mode in macOS has evolved and improved significantly in the last several days and can be tested in recent daily dev builds. Please provide Sukapura Dark theme icons, so that the Sukapura theme can be used also in dark mode – LO uses the Breeze dark theme instead meanwhile because of lacking Sukapura dark theme icons, when automatically detecting dark mode from system settings.
> 
> Yes I have already know this improvement, so that's why I ask TDF staff to fire up a vote to choose existing dark icon theme in macOS dark UI. Visit [the poll.](https://fosstodon.org/@libodesign/109414678200831831) But meantime, there's discussion in Telegram group wether macOS should stick to Sukapura or use Colibre also just like Windows counterpart. I have no strong preference here but the availability of Sukapura Dark version will not occur in a short time.

@Rizal: With joy, I notice recent commits [3fb460b… Dark mode preparation](https://github.com/rizmut/libreoffice-style-sukapura/commit/3fb460bb2fdd32c2724536f50110998e8f59aae0) and [3f862c8… Dark mode preparation](https://github.com/rizmut/libreoffice-style-sukapura/commit/3f862c8b42b7605e0a2dbf0f50b956f373c0b59f) from Feb 27, 2023. Very good, I welcome that! Hooray! What changed your mind, Rizal? Will this change overrule the poll's result and TDF staff decision based on that poll (Breeze dark theme, when system's dark mode is enabled and detected, because of the lacking of a Sukapura dark theme so far), and if yes, when will it be available for testing in LibreOffice daily builds – auto-activated per default, when system's dark mode is detected to give a perfect and in itself consistent Sukapura couple for light and dark mode on macOS?

**Comment by rizmut** [comment]
> @Rizal: With joy, I notice recent commits [3fb460b… Dark mode preparation](https://github.com/rizmut/libreoffice-style-sukapura/commit/3fb460bb2fdd32c2724536f50110998e8f59aae0) and [3f862c8… Dark mode preparation](https://github.com/rizmut/libreoffice-style-sukapura/commit/3f862c8b42b7605e0a2dbf0f50b956f373c0b59f) from Feb 27, 2023. Very good, I welcome that! Hooray! What changed your mind, Rizal? Will this change overrule the poll's result and TDF staff decision based on that poll (Breeze dark theme, when system's dark mode is enabled and detected, because of the lacking of a Sukapura dark theme so far), and if yes, when will it be available for testing in LibreOffice daily builds – auto-activated per default, when system's dark mode is detected to give a perfect and in itself consistent Sukapura couple for light and dark mode on macOS?

Actually I have pushed the Dark variant to the LibreOffice core, although the patch needed polishes a lot. What I don't know yet is whether this variant will be set as default in macOS dark mode technically I entrust the coding part to a contributor from Redhat: Caolan. 

But in terms of the community (non-technically) it is likely that most members will agree with using Sukapura Dark. I won't promise a date, it should be this week or a maximum of next week, you can try it soon. This Redhat friend is a hyperactive contributor at LibreOffice. So, the wait shouldn't be long, I'll need a lot of reports for sure for any deficiencies.

**Comment by sierkb** [comment]
Rizal, thanks a lot! 👍🏻
